### ISSUE TITLE
Add a command line CoffeeScript compiler

### ISSUE THREAD

**Issue by jgibson** [doloopwhile/Python-CoffeeScript#12]
It would be useful to have a command line replacement for the CoffeeScript compiler provided by Node.JS's coffee-script module (coffee --compile). I've [written one](https://gist.github.com/jgibson/36238c1cda8bbeb5aa17), but I don't know how to integrate it into your pip package.

**Comment by doloopwhile** [comment]
We can add `__main__.py` to priovide command line interface.

After adding them, please create a pull-request.
