### ISSUE TITLE
Produce Source Maps

### ISSUE THREAD

**Issue by trvrm** [doloopwhile/Python-CoffeeScript#14]
It would be good to have a `map` flag as well as a `bare` flag to have the option of producing source maps.

**Comment by trvrm** [comment]
I can produce a patch if you like.

**Comment by doloopwhile** [comment]
Source map is nice. However, I have no idea about good interface.

Will you create a pull-request for `map` ?.

**Comment by trvrm** [comment]
I tried yesterday and it turned out to be more complicated than I thought.
