### ISSUE TITLE
Add %load_ext for IPython/Jupyter notebook use

### ISSUE THREAD

**Issue by genomematt** [doloopwhile/Python-CoffeeScript#17]
It would be great to have code for ipython magic e.g. https://gist.github.com/bollwyvl/de3b4ca8b6ed8bb28f86 built directly into this package.

**Comment by doloopwhile** [comment]
It looks good. Will you make a pull request?

**Comment by genomematt** [comment]
It would be much better if you could prod the original author to do it



> On 5 Dec 2015, at 16:53, OMOTO Kenji <notifications@github.com> wrote:
> 
> It looks good. Will you make a pull request?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

______________________________________________________________________
The information in this email is confidential and intended solely for the addressee.
You must not disclose, forward, print or use it without the permission of the sender.
______________________________________________________________________

**Comment by doloopwhile** [comment]
I do not understand IPython and its usage now.

So, it is convenience for me if you sent a pull request.

2015-12-06 8:33 GMT+09:00 Matthew Wakefield <notifications@github.com>:
> It would be much better if you could prod the original author to do it
>
>
>
>> On 5 Dec 2015, at 16:53, OMOTO Kenji <notifications@github.com> wrote:
>>
>> It looks good. Will you make a pull request?
>>
>> —
>> Reply to this email directly or view it on GitHub.
>>
>
> ______________________________________________________________________
> The information in this email is confidential and intended solely for the
> addressee.
> You must not disclose, forward, print or use it without the permission of
> the sender.
> ______________________________________________________________________
>
> —
> Reply to this email directly or view it on GitHub.



-- 
小本健司
OMOTO Kenji
doloopwhile@gmail.com
